<Project>
  <ItemGroup>
    <PackageVersion Remove="Microsoft.CodeAnalysis.PublicApiAnalyzers;Microsoft.SourceLink.GitHub;MinVer" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
  </ItemGroup>
</Project>
